services:
  api:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
      image: "redis/redis-stack:latest"
      ports:
        - "6379:6379"
      # command: ["redis-server", "--loadmodule", "./target/release/librejson.dylib"]      